# deploy
name: GitHub Actions CICD using maven and SL lab 
on: 
 push: 
   branches: ["main"]
 workflow_dispatch: 
jobs: 
  buildandDeploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Clone the Repo 
      uses: actions/checkout@v4 
    - name: Setup JDK 11 and maven 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Build with Maven 
      run: mvn -B package --file pom.xml 
    - name: connect to Jenkins and deploy code on tomcat9
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
       host: 'http://192.168.1.107'
       user: 'pk'
       pass: '12345'
       port: 8080
       connect_timeout: 10s
       # Configure Tomcat Apache for automated code deployment...
       first_ssh: |
          sudo chmod 777 /var/lib/tomcat9/webapps
       scp: |
          './target/*war' => /var/lib/tomcat9/webapps
       last_ssh: |
          sudo systemctl restart tomcat9
